permalink: /posts/:title
markdown: kramdown
remote_theme: rafaell-lycan/rafaell-lycan.com

gems:
  - jekyll-sitemap

name: Daniel S.
url: https://daniel.eu.com 
description: Programmer from the planet Earth.
twitter: moodpepper
